language: node_js
node_js:
- '0.10'
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install
- node node_modules/bower/bin/bower install
- cd test
- node ../node_modules/bower/bin/bower install
- cd ..
- sleep 1
script:
- node node_modules/karma/bin/karma start karma.conf.js --no-auto-watch --single-run
  --reporters=dots --browsers=Firefox
- node node_modules/gulp/bin/gulp
deploy:
  provider: divshot
  api_key:
    secure: g1QuGEQERR7Z9P/QxqhK1IitYrq0f30n+L0ZGMU4Dpqz+ALthEON0tcLYv3HGjUz13qejbIoZFoxkT5mVz1CyJZQINaoBQdJRgG65mqqgvfRdlqLSGrXLMX0Wc97ogH6+P9mG1RcJ8KvG4LU8Qd0GJoHmOv2PQCqmaj31393pFQi/2+hv7pymQ1lK/sFBTewUMuZqcPdDJHZAf91pgJrCKe6DoiMlVs2LkUMSsJQkoto23XBaT4Bz9vTZGcWhOB8/QXwC5kVh7P0sj1wikdQmK4v38/fuHrRQnddKA3SMv/QAH9PQ/gMkzC8+0tE51L+h+52VV+J2gQTcqlzgwrseTmrAGiY5gF42zzn5YJeqGdgq1mhBXQjmoobkSDbTYjeRCk6iRtJ1jhErg3CFvMrp6jCImmpp8VHZRL30V7R3HZ+amrSUA9m5G8zvboCsDZQ+UrXVEMx3RR7xvDIsYBBRjNnQ+fKgdx8zbDO6PWYwD2q8hUZ188jE3w8kxkxLcoZt4/uHPn8tX2ZmCxG2Kn3EMeVPf3A3WRdeLRYSNOVfH434NtSUmdv0oCQbvGKnUiAFzQC0pXFqkXGVCm8UQjRkoUkdCWiiJ7UmxQENaSPb9fSkp1aDuFmAHJxbv4M/lJtD5CKTwXJ94OqgGYAGB/m1KrdoXSu/YBOfLoO7l/6SVw=
  environment:
    master: development
  skip_cleanup: true
